apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    project: roboshop
    purpose: dp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: dp-demo
      project: roboshop
  template:
    metadata:
      labels:
        purpose: dp-demo
        project: roboshop

    spec:
      containers:
      - name: nginx
        image: nginx:latest
