apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    project: roboshop
    purpose: taints-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      purpose: taints-demo
  template:
    metadata:
      labels:
        project: roboshop
        purpose: taints-demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest