apiVersion: apps/v1
kind: Deployment
metadata:
  name: taints-tolerations
  labels:
    project: roboshop
    purpose: tolerations-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      purpose: tolerations-demo
  template:
    metadata:
      labels:
        project: roboshop
        purpose: tolerations-demo
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-24-134.ec2.internal
      containers:
      - name: nginx
        image: nginx:latest